### ISSUE TITLE
update MariaDB

### ISSUE THREAD

**Issue by StephanKrauss** [wangxian/alpine-mysql#10]
Hello,

is there a simple way to update the MariaDB.
In the container run the version 10.1.19 .
the latest version is 10.3 .

Can you help.

Your sincerly

Stephan

**Comment by wangxian** [comment]
Please pull request

**Comment by takman1** [comment]
You have to build your own image (assumes you have docker installed locally) :
- `mkdir /tmp/alpine-mysql && cd /tmp/alpine-mysql`
- `git clone https://github.com/wangxian/alpine-mysql.git .`
- `docker build --no-cache . -t local/wangxian/alpine-mysql:latest`
- `docker run -d --rm --name mysql -p 3306:3306 -v $(pwd):/app -e MYSQL_DATABASE=test_db -e MYSQL_USER=db_user -e MYSQL_PASSWORD=db_password -e MYSQL_ROOT_PASSWORD=db_root_password local/wangxian/alpine-mysql:latest`

To check MariaDB version : 
- `docker exec -it mysql mysql --version`

Hope this helps you.
