### ISSUE TITLE
Can't start server : Bind on unix socket: No such file or directory

### ISSUE THREAD

**Issue by lijian186** [wangxian/alpine-mysql#4]
[ERROR] Can't start server : Bind on unix socket: No such file or directory
[ERROR] Do you already have another mysqld server running on socket: /run/mysqld/mysqld.sock ?
[ERROR] Aborting

**Comment by lloydzhou** [comment]
mkdir /run/mysqld

**Comment by dmuth** [comment]
@lloydzhou's comment works when in interactive mode. :-)

**Comment by davideferre** [comment]
I've opened pull request #9 to solve this problem adding a line in my.cnf.

**Comment by flexchar** [comment]
Turns out I end up with a folder instead of a file...
`rm -r /run/mysqld/mysqld.sock && mkdir -p /run/mysqld && chown -R mysql:mysql /run/mysqld`
