### ISSUE TITLE
This is MariaDB, not MySQL. You should add a note in the readme

### ISSUE THREAD

**Issue by marcj** [wangxian/alpine-mysql#6]

**Comment by davideferre** [comment]
I've opened pull request #9 to solve this problem adding a line in my.cnf.

**Comment by marcj** [comment]
#9 is not related in any way to this issue.

**Comment by davideferre** [comment]
Sorry I've confused this issue with issue #4 .

**Comment by wangxian** [comment]
It's too long, I'm going to close the issue

**Comment by marcj** [comment]
What do you mean its too long?
MySQL and MariaDB are different databases, although latter supports the protocol of MySQL it does not fully support MySQL so this package name is not only misleading but plain wrong. MariaDB has different default settings which makes it entirely different especially dor ORM/migration libraries.
